/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'auth.register': {
    methods: ["GET","HEAD"],
    pattern: '/auth/register',
    tokens: [{"old":"/auth/register","type":0,"val":"auth","end":""},{"old":"/auth/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['auth.register']['types'],
  },
  'auth.postRegister': {
    methods: ["POST"],
    pattern: '/auth/register',
    tokens: [{"old":"/auth/register","type":0,"val":"auth","end":""},{"old":"/auth/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['auth.postRegister']['types'],
  },
  'auth.login': {
    methods: ["GET","HEAD"],
    pattern: '/auth/login',
    tokens: [{"old":"/auth/login","type":0,"val":"auth","end":""},{"old":"/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.login']['types'],
  },
  'auth.postLogin': {
    methods: ["POST"],
    pattern: '/auth/login',
    tokens: [{"old":"/auth/login","type":0,"val":"auth","end":""},{"old":"/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.postLogin']['types'],
  },
  'auth.logout': {
    methods: ["GET","HEAD"],
    pattern: '/auth/logout',
    tokens: [{"old":"/auth/logout","type":0,"val":"auth","end":""},{"old":"/auth/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['auth.logout']['types'],
  },
  'home.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin',
    tokens: [{"old":"/admin","type":0,"val":"admin","end":""}],
    types: placeholder as Registry['home.index']['types'],
  },
  'users.me': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users/me',
    tokens: [{"old":"/admin/users/me","type":0,"val":"admin","end":""},{"old":"/admin/users/me","type":0,"val":"users","end":""},{"old":"/admin/users/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['users.me']['types'],
  },
  'users.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users',
    tokens: [{"old":"/admin/users","type":0,"val":"admin","end":""},{"old":"/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['users.index']['types'],
  },
  'users.store': {
    methods: ["POST"],
    pattern: '/admin/users',
    tokens: [{"old":"/admin/users","type":0,"val":"admin","end":""},{"old":"/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['users.store']['types'],
  },
  'users.getJson': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users/get-json',
    tokens: [{"old":"/admin/users/get-json","type":0,"val":"admin","end":""},{"old":"/admin/users/get-json","type":0,"val":"users","end":""},{"old":"/admin/users/get-json","type":0,"val":"get-json","end":""}],
    types: placeholder as Registry['users.getJson']['types'],
  },
  'users.delete': {
    methods: ["DELETE"],
    pattern: '/admin/users/:id',
    tokens: [{"old":"/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/admin/users/:id","type":0,"val":"users","end":""},{"old":"/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['users.delete']['types'],
  },
  'users.update': {
    methods: ["PATCH"],
    pattern: '/admin/users/:id',
    tokens: [{"old":"/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/admin/users/:id","type":0,"val":"users","end":""},{"old":"/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['users.update']['types'],
  },
  'users.addBalance': {
    methods: ["POST"],
    pattern: '/admin/users/:id/add-balance',
    tokens: [{"old":"/admin/users/:id/add-balance","type":0,"val":"admin","end":""},{"old":"/admin/users/:id/add-balance","type":0,"val":"users","end":""},{"old":"/admin/users/:id/add-balance","type":1,"val":"id","end":""},{"old":"/admin/users/:id/add-balance","type":0,"val":"add-balance","end":""}],
    types: placeholder as Registry['users.addBalance']['types'],
  },
  'users.deductBalance': {
    methods: ["POST"],
    pattern: '/admin/users/:id/deduct-balance',
    tokens: [{"old":"/admin/users/:id/deduct-balance","type":0,"val":"admin","end":""},{"old":"/admin/users/:id/deduct-balance","type":0,"val":"users","end":""},{"old":"/admin/users/:id/deduct-balance","type":1,"val":"id","end":""},{"old":"/admin/users/:id/deduct-balance","type":0,"val":"deduct-balance","end":""}],
    types: placeholder as Registry['users.deductBalance']['types'],
  },
  'productCategories.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories',
    tokens: [{"old":"/admin/product-categories","type":0,"val":"admin","end":""},{"old":"/admin/product-categories","type":0,"val":"product-categories","end":""}],
    types: placeholder as Registry['productCategories.index']['types'],
  },
  'productCategories.indexGames': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/game',
    tokens: [{"old":"/admin/product-categories/game","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/game","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/game","type":0,"val":"game","end":""}],
    types: placeholder as Registry['productCategories.indexGames']['types'],
  },
  'productCategories.createGame': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/game/create',
    tokens: [{"old":"/admin/product-categories/game/create","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/game/create","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/game/create","type":0,"val":"game","end":""},{"old":"/admin/product-categories/game/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['productCategories.createGame']['types'],
  },
  'productCategories.editGame': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/game/:id/edit',
    tokens: [{"old":"/admin/product-categories/game/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/game/:id/edit","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/game/:id/edit","type":0,"val":"game","end":""},{"old":"/admin/product-categories/game/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/product-categories/game/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['productCategories.editGame']['types'],
  },
  'productCategories.indexPulsa': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/pulsa',
    tokens: [{"old":"/admin/product-categories/pulsa","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/pulsa","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/pulsa","type":0,"val":"pulsa","end":""}],
    types: placeholder as Registry['productCategories.indexPulsa']['types'],
  },
  'productCategories.createPulsa': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/pulsa/create',
    tokens: [{"old":"/admin/product-categories/pulsa/create","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/pulsa/create","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/pulsa/create","type":0,"val":"pulsa","end":""},{"old":"/admin/product-categories/pulsa/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['productCategories.createPulsa']['types'],
  },
  'productCategories.editPulsa': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/pulsa/:id/edit',
    tokens: [{"old":"/admin/product-categories/pulsa/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/pulsa/:id/edit","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/pulsa/:id/edit","type":0,"val":"pulsa","end":""},{"old":"/admin/product-categories/pulsa/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/product-categories/pulsa/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['productCategories.editPulsa']['types'],
  },
  'productCategories.indexKuota': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/kuota',
    tokens: [{"old":"/admin/product-categories/kuota","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/kuota","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/kuota","type":0,"val":"kuota","end":""}],
    types: placeholder as Registry['productCategories.indexKuota']['types'],
  },
  'productCategories.createKuota': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/kuota/create',
    tokens: [{"old":"/admin/product-categories/kuota/create","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/kuota/create","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/kuota/create","type":0,"val":"kuota","end":""},{"old":"/admin/product-categories/kuota/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['productCategories.createKuota']['types'],
  },
  'productCategories.editKuota': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/kuota/:id/edit',
    tokens: [{"old":"/admin/product-categories/kuota/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/kuota/:id/edit","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/kuota/:id/edit","type":0,"val":"kuota","end":""},{"old":"/admin/product-categories/kuota/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/product-categories/kuota/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['productCategories.editKuota']['types'],
  },
  'productCategories.indexTokenPln': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/token-pln',
    tokens: [{"old":"/admin/product-categories/token-pln","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/token-pln","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/token-pln","type":0,"val":"token-pln","end":""}],
    types: placeholder as Registry['productCategories.indexTokenPln']['types'],
  },
  'productCategories.createTokenPln': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/token-pln/create',
    tokens: [{"old":"/admin/product-categories/token-pln/create","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/token-pln/create","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/token-pln/create","type":0,"val":"token-pln","end":""},{"old":"/admin/product-categories/token-pln/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['productCategories.createTokenPln']['types'],
  },
  'productCategories.editTokenPln': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/token-pln/:id/edit',
    tokens: [{"old":"/admin/product-categories/token-pln/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/token-pln/:id/edit","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/token-pln/:id/edit","type":0,"val":"token-pln","end":""},{"old":"/admin/product-categories/token-pln/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/product-categories/token-pln/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['productCategories.editTokenPln']['types'],
  },
  'productCategories.indexEWallet': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/e-wallet',
    tokens: [{"old":"/admin/product-categories/e-wallet","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/e-wallet","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/e-wallet","type":0,"val":"e-wallet","end":""}],
    types: placeholder as Registry['productCategories.indexEWallet']['types'],
  },
  'productCategories.createEWallet': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/e-wallet/create',
    tokens: [{"old":"/admin/product-categories/e-wallet/create","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/e-wallet/create","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/e-wallet/create","type":0,"val":"e-wallet","end":""},{"old":"/admin/product-categories/e-wallet/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['productCategories.createEWallet']['types'],
  },
  'productCategories.editEWallet': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/e-wallet/:id/edit',
    tokens: [{"old":"/admin/product-categories/e-wallet/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/e-wallet/:id/edit","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/e-wallet/:id/edit","type":0,"val":"e-wallet","end":""},{"old":"/admin/product-categories/e-wallet/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/product-categories/e-wallet/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['productCategories.editEWallet']['types'],
  },
  'productCategories.indexVoucher': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/voucher',
    tokens: [{"old":"/admin/product-categories/voucher","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/voucher","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/voucher","type":0,"val":"voucher","end":""}],
    types: placeholder as Registry['productCategories.indexVoucher']['types'],
  },
  'productCategories.createVoucher': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/voucher/create',
    tokens: [{"old":"/admin/product-categories/voucher/create","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/voucher/create","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/voucher/create","type":0,"val":"voucher","end":""},{"old":"/admin/product-categories/voucher/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['productCategories.createVoucher']['types'],
  },
  'productCategories.editVoucher': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/voucher/:id/edit',
    tokens: [{"old":"/admin/product-categories/voucher/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/voucher/:id/edit","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/voucher/:id/edit","type":0,"val":"voucher","end":""},{"old":"/admin/product-categories/voucher/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/product-categories/voucher/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['productCategories.editVoucher']['types'],
  },
  'productCategories.indexOtherPrepaid': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/other-prepaid',
    tokens: [{"old":"/admin/product-categories/other-prepaid","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/other-prepaid","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/other-prepaid","type":0,"val":"other-prepaid","end":""}],
    types: placeholder as Registry['productCategories.indexOtherPrepaid']['types'],
  },
  'productCategories.createOtherPrepaid': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/other-prepaid/create',
    tokens: [{"old":"/admin/product-categories/other-prepaid/create","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/other-prepaid/create","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/other-prepaid/create","type":0,"val":"other-prepaid","end":""},{"old":"/admin/product-categories/other-prepaid/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['productCategories.createOtherPrepaid']['types'],
  },
  'productCategories.editOtherPrepaid': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/other-prepaid/:id/edit',
    tokens: [{"old":"/admin/product-categories/other-prepaid/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/other-prepaid/:id/edit","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/other-prepaid/:id/edit","type":0,"val":"other-prepaid","end":""},{"old":"/admin/product-categories/other-prepaid/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/product-categories/other-prepaid/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['productCategories.editOtherPrepaid']['types'],
  },
  'productCategories.indexPostpaidTagihanPln': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/postpaid/tagihan-pln',
    tokens: [{"old":"/admin/product-categories/postpaid/tagihan-pln","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/postpaid/tagihan-pln","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/postpaid/tagihan-pln","type":0,"val":"postpaid","end":""},{"old":"/admin/product-categories/postpaid/tagihan-pln","type":0,"val":"tagihan-pln","end":""}],
    types: placeholder as Registry['productCategories.indexPostpaidTagihanPln']['types'],
  },
  'productCategories.createPostpaidTagihanPln': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/postpaid/tagihan-pln/create',
    tokens: [{"old":"/admin/product-categories/postpaid/tagihan-pln/create","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/postpaid/tagihan-pln/create","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/postpaid/tagihan-pln/create","type":0,"val":"postpaid","end":""},{"old":"/admin/product-categories/postpaid/tagihan-pln/create","type":0,"val":"tagihan-pln","end":""},{"old":"/admin/product-categories/postpaid/tagihan-pln/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['productCategories.createPostpaidTagihanPln']['types'],
  },
  'productCategories.editPostpaidTagihanPln': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/postpaid/tagihan-pln/:id/edit',
    tokens: [{"old":"/admin/product-categories/postpaid/tagihan-pln/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/postpaid/tagihan-pln/:id/edit","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/postpaid/tagihan-pln/:id/edit","type":0,"val":"postpaid","end":""},{"old":"/admin/product-categories/postpaid/tagihan-pln/:id/edit","type":0,"val":"tagihan-pln","end":""},{"old":"/admin/product-categories/postpaid/tagihan-pln/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/product-categories/postpaid/tagihan-pln/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['productCategories.editPostpaidTagihanPln']['types'],
  },
  'productCategories.indexPostpaidPDAM': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/postpaid/pdam',
    tokens: [{"old":"/admin/product-categories/postpaid/pdam","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/postpaid/pdam","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/postpaid/pdam","type":0,"val":"postpaid","end":""},{"old":"/admin/product-categories/postpaid/pdam","type":0,"val":"pdam","end":""}],
    types: placeholder as Registry['productCategories.indexPostpaidPDAM']['types'],
  },
  'productCategories.createPostpaidPDAM': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/postpaid/pdam/create',
    tokens: [{"old":"/admin/product-categories/postpaid/pdam/create","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/postpaid/pdam/create","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/postpaid/pdam/create","type":0,"val":"postpaid","end":""},{"old":"/admin/product-categories/postpaid/pdam/create","type":0,"val":"pdam","end":""},{"old":"/admin/product-categories/postpaid/pdam/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['productCategories.createPostpaidPDAM']['types'],
  },
  'productCategories.editPostpaidPDAM': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/postpaid/pdam/:id/edit',
    tokens: [{"old":"/admin/product-categories/postpaid/pdam/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/postpaid/pdam/:id/edit","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/postpaid/pdam/:id/edit","type":0,"val":"postpaid","end":""},{"old":"/admin/product-categories/postpaid/pdam/:id/edit","type":0,"val":"pdam","end":""},{"old":"/admin/product-categories/postpaid/pdam/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/product-categories/postpaid/pdam/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['productCategories.editPostpaidPDAM']['types'],
  },
  'productCategories.indexPostpaidInternet': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/postpaid/internet',
    tokens: [{"old":"/admin/product-categories/postpaid/internet","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/postpaid/internet","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/postpaid/internet","type":0,"val":"postpaid","end":""},{"old":"/admin/product-categories/postpaid/internet","type":0,"val":"internet","end":""}],
    types: placeholder as Registry['productCategories.indexPostpaidInternet']['types'],
  },
  'productCategories.createPostpaidInternet': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/postpaid/internet/create',
    tokens: [{"old":"/admin/product-categories/postpaid/internet/create","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/postpaid/internet/create","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/postpaid/internet/create","type":0,"val":"postpaid","end":""},{"old":"/admin/product-categories/postpaid/internet/create","type":0,"val":"internet","end":""},{"old":"/admin/product-categories/postpaid/internet/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['productCategories.createPostpaidInternet']['types'],
  },
  'productCategories.editPostpaidInternet': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/postpaid/internet/:id/edit',
    tokens: [{"old":"/admin/product-categories/postpaid/internet/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/postpaid/internet/:id/edit","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/postpaid/internet/:id/edit","type":0,"val":"postpaid","end":""},{"old":"/admin/product-categories/postpaid/internet/:id/edit","type":0,"val":"internet","end":""},{"old":"/admin/product-categories/postpaid/internet/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/product-categories/postpaid/internet/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['productCategories.editPostpaidInternet']['types'],
  },
  'productCategories.indexPostpaidBPJSKesehatan': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/postpaid/bpjs-kesehatan',
    tokens: [{"old":"/admin/product-categories/postpaid/bpjs-kesehatan","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/postpaid/bpjs-kesehatan","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/postpaid/bpjs-kesehatan","type":0,"val":"postpaid","end":""},{"old":"/admin/product-categories/postpaid/bpjs-kesehatan","type":0,"val":"bpjs-kesehatan","end":""}],
    types: placeholder as Registry['productCategories.indexPostpaidBPJSKesehatan']['types'],
  },
  'productCategories.createPostpaidBPJSKesehatan': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/postpaid/bpjs-kesehatan/create',
    tokens: [{"old":"/admin/product-categories/postpaid/bpjs-kesehatan/create","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/postpaid/bpjs-kesehatan/create","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/postpaid/bpjs-kesehatan/create","type":0,"val":"postpaid","end":""},{"old":"/admin/product-categories/postpaid/bpjs-kesehatan/create","type":0,"val":"bpjs-kesehatan","end":""},{"old":"/admin/product-categories/postpaid/bpjs-kesehatan/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['productCategories.createPostpaidBPJSKesehatan']['types'],
  },
  'productCategories.editPostpaidBPJSKesehatan': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/postpaid/bpjs-kesehatan/:id/edit',
    tokens: [{"old":"/admin/product-categories/postpaid/bpjs-kesehatan/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/postpaid/bpjs-kesehatan/:id/edit","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/postpaid/bpjs-kesehatan/:id/edit","type":0,"val":"postpaid","end":""},{"old":"/admin/product-categories/postpaid/bpjs-kesehatan/:id/edit","type":0,"val":"bpjs-kesehatan","end":""},{"old":"/admin/product-categories/postpaid/bpjs-kesehatan/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/product-categories/postpaid/bpjs-kesehatan/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['productCategories.editPostpaidBPJSKesehatan']['types'],
  },
  'productCategories.indexPostpaidBPJSKetenagakerjaan': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/postpaid/bpjs-ketenagakerjaan',
    tokens: [{"old":"/admin/product-categories/postpaid/bpjs-ketenagakerjaan","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/postpaid/bpjs-ketenagakerjaan","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/postpaid/bpjs-ketenagakerjaan","type":0,"val":"postpaid","end":""},{"old":"/admin/product-categories/postpaid/bpjs-ketenagakerjaan","type":0,"val":"bpjs-ketenagakerjaan","end":""}],
    types: placeholder as Registry['productCategories.indexPostpaidBPJSKetenagakerjaan']['types'],
  },
  'productCategories.createPostpaidBPJSKetenagakerjaan': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/postpaid/bpjs-ketenagakerjaan/create',
    tokens: [{"old":"/admin/product-categories/postpaid/bpjs-ketenagakerjaan/create","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/postpaid/bpjs-ketenagakerjaan/create","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/postpaid/bpjs-ketenagakerjaan/create","type":0,"val":"postpaid","end":""},{"old":"/admin/product-categories/postpaid/bpjs-ketenagakerjaan/create","type":0,"val":"bpjs-ketenagakerjaan","end":""},{"old":"/admin/product-categories/postpaid/bpjs-ketenagakerjaan/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['productCategories.createPostpaidBPJSKetenagakerjaan']['types'],
  },
  'productCategories.editPostpaidBPJSKetenagakerjaan': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/postpaid/bpjs-ketenagakerjaan/:id/edit',
    tokens: [{"old":"/admin/product-categories/postpaid/bpjs-ketenagakerjaan/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/postpaid/bpjs-ketenagakerjaan/:id/edit","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/postpaid/bpjs-ketenagakerjaan/:id/edit","type":0,"val":"postpaid","end":""},{"old":"/admin/product-categories/postpaid/bpjs-ketenagakerjaan/:id/edit","type":0,"val":"bpjs-ketenagakerjaan","end":""},{"old":"/admin/product-categories/postpaid/bpjs-ketenagakerjaan/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/product-categories/postpaid/bpjs-ketenagakerjaan/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['productCategories.editPostpaidBPJSKetenagakerjaan']['types'],
  },
  'productCategories.getProductCategoryByCategoryNameJson': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/get-json',
    tokens: [{"old":"/admin/product-categories/get-json","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/get-json","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/get-json","type":0,"val":"get-json","end":""}],
    types: placeholder as Registry['productCategories.getProductCategoryByCategoryNameJson']['types'],
  },
  'productCategories.detailWithBillingType': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/:billingType/:type/:id',
    tokens: [{"old":"/admin/product-categories/:billingType/:type/:id","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/:billingType/:type/:id","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/:billingType/:type/:id","type":1,"val":"billingType","end":""},{"old":"/admin/product-categories/:billingType/:type/:id","type":1,"val":"type","end":""},{"old":"/admin/product-categories/:billingType/:type/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['productCategories.detailWithBillingType']['types'],
  },
  'productCategories.detail': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-categories/:type/:id',
    tokens: [{"old":"/admin/product-categories/:type/:id","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/:type/:id","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/:type/:id","type":1,"val":"type","end":""},{"old":"/admin/product-categories/:type/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['productCategories.detail']['types'],
  },
  'productCategories.postCreate': {
    methods: ["POST"],
    pattern: '/admin/product-categories/:type/create',
    tokens: [{"old":"/admin/product-categories/:type/create","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/:type/create","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/:type/create","type":1,"val":"type","end":""},{"old":"/admin/product-categories/:type/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['productCategories.postCreate']['types'],
  },
  'productCategories.postEdit': {
    methods: ["PATCH"],
    pattern: '/admin/product-categories/:type/:id',
    tokens: [{"old":"/admin/product-categories/:type/:id","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/:type/:id","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/:type/:id","type":1,"val":"type","end":""},{"old":"/admin/product-categories/:type/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['productCategories.postEdit']['types'],
  },
  'productCategories.delete': {
    methods: ["DELETE"],
    pattern: '/admin/product-categories/:type/:id',
    tokens: [{"old":"/admin/product-categories/:type/:id","type":0,"val":"admin","end":""},{"old":"/admin/product-categories/:type/:id","type":0,"val":"product-categories","end":""},{"old":"/admin/product-categories/:type/:id","type":1,"val":"type","end":""},{"old":"/admin/product-categories/:type/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['productCategories.delete']['types'],
  },
  'fileManagers.list': {
    methods: ["GET","HEAD"],
    pattern: '/admin/file-managers',
    tokens: [{"old":"/admin/file-managers","type":0,"val":"admin","end":""},{"old":"/admin/file-managers","type":0,"val":"file-managers","end":""}],
    types: placeholder as Registry['fileManagers.list']['types'],
  },
  'fileManagers.delete': {
    methods: ["DELETE"],
    pattern: '/admin/file-managers/:id',
    tokens: [{"old":"/admin/file-managers/:id","type":0,"val":"admin","end":""},{"old":"/admin/file-managers/:id","type":0,"val":"file-managers","end":""},{"old":"/admin/file-managers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['fileManagers.delete']['types'],
  },
  'fileManagers.upload': {
    methods: ["POST"],
    pattern: '/admin/file-managers/upload',
    tokens: [{"old":"/admin/file-managers/upload","type":0,"val":"admin","end":""},{"old":"/admin/file-managers/upload","type":0,"val":"file-managers","end":""},{"old":"/admin/file-managers/upload","type":0,"val":"upload","end":""}],
    types: placeholder as Registry['fileManagers.upload']['types'],
  },
  'fileManagers.uploadMany': {
    methods: ["POST"],
    pattern: '/admin/file-managers/upload-many',
    tokens: [{"old":"/admin/file-managers/upload-many","type":0,"val":"admin","end":""},{"old":"/admin/file-managers/upload-many","type":0,"val":"file-managers","end":""},{"old":"/admin/file-managers/upload-many","type":0,"val":"upload-many","end":""}],
    types: placeholder as Registry['fileManagers.uploadMany']['types'],
  },
  'fileManagers.deleteBulk': {
    methods: ["POST"],
    pattern: '/admin/file-managers/delete-bulk',
    tokens: [{"old":"/admin/file-managers/delete-bulk","type":0,"val":"admin","end":""},{"old":"/admin/file-managers/delete-bulk","type":0,"val":"file-managers","end":""},{"old":"/admin/file-managers/delete-bulk","type":0,"val":"delete-bulk","end":""}],
    types: placeholder as Registry['fileManagers.deleteBulk']['types'],
  },
  'fileManagers.getById': {
    methods: ["GET","HEAD"],
    pattern: '/admin/file-managers/:id',
    tokens: [{"old":"/admin/file-managers/:id","type":0,"val":"admin","end":""},{"old":"/admin/file-managers/:id","type":0,"val":"file-managers","end":""},{"old":"/admin/file-managers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['fileManagers.getById']['types'],
  },
  'inputFields.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/input-fields',
    tokens: [{"old":"/admin/input-fields","type":0,"val":"admin","end":""},{"old":"/admin/input-fields","type":0,"val":"input-fields","end":""}],
    types: placeholder as Registry['inputFields.index']['types'],
  },
  'inputFields.postCreate': {
    methods: ["POST"],
    pattern: '/admin/input-fields',
    tokens: [{"old":"/admin/input-fields","type":0,"val":"admin","end":""},{"old":"/admin/input-fields","type":0,"val":"input-fields","end":""}],
    types: placeholder as Registry['inputFields.postCreate']['types'],
  },
  'inputFields.getAll': {
    methods: ["GET","HEAD"],
    pattern: '/admin/input-fields/all',
    tokens: [{"old":"/admin/input-fields/all","type":0,"val":"admin","end":""},{"old":"/admin/input-fields/all","type":0,"val":"input-fields","end":""},{"old":"/admin/input-fields/all","type":0,"val":"all","end":""}],
    types: placeholder as Registry['inputFields.getAll']['types'],
  },
  'inputFields.postConnect': {
    methods: ["POST"],
    pattern: '/admin/input-fields/connect',
    tokens: [{"old":"/admin/input-fields/connect","type":0,"val":"admin","end":""},{"old":"/admin/input-fields/connect","type":0,"val":"input-fields","end":""},{"old":"/admin/input-fields/connect","type":0,"val":"connect","end":""}],
    types: placeholder as Registry['inputFields.postConnect']['types'],
  },
  'inputFields.postDisconnect': {
    methods: ["DELETE"],
    pattern: '/admin/input-fields/disconnect/:id',
    tokens: [{"old":"/admin/input-fields/disconnect/:id","type":0,"val":"admin","end":""},{"old":"/admin/input-fields/disconnect/:id","type":0,"val":"input-fields","end":""},{"old":"/admin/input-fields/disconnect/:id","type":0,"val":"disconnect","end":""},{"old":"/admin/input-fields/disconnect/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['inputFields.postDisconnect']['types'],
  },
  'inputFields.postUpdate': {
    methods: ["PATCH"],
    pattern: '/admin/input-fields/:id',
    tokens: [{"old":"/admin/input-fields/:id","type":0,"val":"admin","end":""},{"old":"/admin/input-fields/:id","type":0,"val":"input-fields","end":""},{"old":"/admin/input-fields/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['inputFields.postUpdate']['types'],
  },
  'inputFields.delete': {
    methods: ["DELETE"],
    pattern: '/admin/input-fields/:id',
    tokens: [{"old":"/admin/input-fields/:id","type":0,"val":"admin","end":""},{"old":"/admin/input-fields/:id","type":0,"val":"input-fields","end":""},{"old":"/admin/input-fields/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['inputFields.delete']['types'],
  },
  'productSubCategories.postCreate': {
    methods: ["POST"],
    pattern: '/admin/product-sub-categories',
    tokens: [{"old":"/admin/product-sub-categories","type":0,"val":"admin","end":""},{"old":"/admin/product-sub-categories","type":0,"val":"product-sub-categories","end":""}],
    types: placeholder as Registry['productSubCategories.postCreate']['types'],
  },
  'productSubCategories.detail': {
    methods: ["GET","HEAD"],
    pattern: '/admin/product-sub-categories/:id',
    tokens: [{"old":"/admin/product-sub-categories/:id","type":0,"val":"admin","end":""},{"old":"/admin/product-sub-categories/:id","type":0,"val":"product-sub-categories","end":""},{"old":"/admin/product-sub-categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['productSubCategories.detail']['types'],
  },
  'productSubCategories.postUpdate': {
    methods: ["PATCH"],
    pattern: '/admin/product-sub-categories/:id',
    tokens: [{"old":"/admin/product-sub-categories/:id","type":0,"val":"admin","end":""},{"old":"/admin/product-sub-categories/:id","type":0,"val":"product-sub-categories","end":""},{"old":"/admin/product-sub-categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['productSubCategories.postUpdate']['types'],
  },
  'productSubCategories.delete': {
    methods: ["DELETE"],
    pattern: '/admin/product-sub-categories/:id',
    tokens: [{"old":"/admin/product-sub-categories/:id","type":0,"val":"admin","end":""},{"old":"/admin/product-sub-categories/:id","type":0,"val":"product-sub-categories","end":""},{"old":"/admin/product-sub-categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['productSubCategories.delete']['types'],
  },
  'products.postCreate': {
    methods: ["POST"],
    pattern: '/admin/products',
    tokens: [{"old":"/admin/products","type":0,"val":"admin","end":""},{"old":"/admin/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['products.postCreate']['types'],
  },
  'products.getAll': {
    methods: ["GET","HEAD"],
    pattern: '/admin/products/all',
    tokens: [{"old":"/admin/products/all","type":0,"val":"admin","end":""},{"old":"/admin/products/all","type":0,"val":"products","end":""},{"old":"/admin/products/all","type":0,"val":"all","end":""}],
    types: placeholder as Registry['products.getAll']['types'],
  },
  'products.getProductByCategoryNameJson': {
    methods: ["GET","HEAD"],
    pattern: '/admin/products/get-json',
    tokens: [{"old":"/admin/products/get-json","type":0,"val":"admin","end":""},{"old":"/admin/products/get-json","type":0,"val":"products","end":""},{"old":"/admin/products/get-json","type":0,"val":"get-json","end":""}],
    types: placeholder as Registry['products.getProductByCategoryNameJson']['types'],
  },
  'products.exists': {
    methods: ["GET","HEAD"],
    pattern: '/admin/products/existing',
    tokens: [{"old":"/admin/products/existing","type":0,"val":"admin","end":""},{"old":"/admin/products/existing","type":0,"val":"products","end":""},{"old":"/admin/products/existing","type":0,"val":"existing","end":""}],
    types: placeholder as Registry['products.exists']['types'],
  },
  'products.providerMap': {
    methods: ["GET","HEAD"],
    pattern: '/admin/products/provider-map',
    tokens: [{"old":"/admin/products/provider-map","type":0,"val":"admin","end":""},{"old":"/admin/products/provider-map","type":0,"val":"products","end":""},{"old":"/admin/products/provider-map","type":0,"val":"provider-map","end":""}],
    types: placeholder as Registry['products.providerMap']['types'],
  },
  'products.detail': {
    methods: ["GET","HEAD"],
    pattern: '/admin/products/:id',
    tokens: [{"old":"/admin/products/:id","type":0,"val":"admin","end":""},{"old":"/admin/products/:id","type":0,"val":"products","end":""},{"old":"/admin/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['products.detail']['types'],
  },
  'products.postEdit': {
    methods: ["PATCH"],
    pattern: '/admin/products/:id',
    tokens: [{"old":"/admin/products/:id","type":0,"val":"admin","end":""},{"old":"/admin/products/:id","type":0,"val":"products","end":""},{"old":"/admin/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['products.postEdit']['types'],
  },
  'products.postUpdateIsAvailable': {
    methods: ["PATCH"],
    pattern: '/admin/products/:id/update-is-available',
    tokens: [{"old":"/admin/products/:id/update-is-available","type":0,"val":"admin","end":""},{"old":"/admin/products/:id/update-is-available","type":0,"val":"products","end":""},{"old":"/admin/products/:id/update-is-available","type":1,"val":"id","end":""},{"old":"/admin/products/:id/update-is-available","type":0,"val":"update-is-available","end":""}],
    types: placeholder as Registry['products.postUpdateIsAvailable']['types'],
  },
  'products.updateProviderPrice': {
    methods: ["PATCH"],
    pattern: '/admin/products/:id/update-provider-price',
    tokens: [{"old":"/admin/products/:id/update-provider-price","type":0,"val":"admin","end":""},{"old":"/admin/products/:id/update-provider-price","type":0,"val":"products","end":""},{"old":"/admin/products/:id/update-provider-price","type":1,"val":"id","end":""},{"old":"/admin/products/:id/update-provider-price","type":0,"val":"update-provider-price","end":""}],
    types: placeholder as Registry['products.updateProviderPrice']['types'],
  },
  'products.delete': {
    methods: ["DELETE"],
    pattern: '/admin/products/:id',
    tokens: [{"old":"/admin/products/:id","type":0,"val":"admin","end":""},{"old":"/admin/products/:id","type":0,"val":"products","end":""},{"old":"/admin/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['products.delete']['types'],
  },
  'providers.digiflazz_products': {
    methods: ["GET","HEAD"],
    pattern: '/admin/providers/digiflazz/products',
    tokens: [{"old":"/admin/providers/digiflazz/products","type":0,"val":"admin","end":""},{"old":"/admin/providers/digiflazz/products","type":0,"val":"providers","end":""},{"old":"/admin/providers/digiflazz/products","type":0,"val":"digiflazz","end":""},{"old":"/admin/providers/digiflazz/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['providers.digiflazz_products']['types'],
  },
  'payments.categories.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/payments/categories',
    tokens: [{"old":"/admin/payments/categories","type":0,"val":"admin","end":""},{"old":"/admin/payments/categories","type":0,"val":"payments","end":""},{"old":"/admin/payments/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['payments.categories.index']['types'],
  },
  'payments.categories.postCreate': {
    methods: ["POST"],
    pattern: '/admin/payments/categories',
    tokens: [{"old":"/admin/payments/categories","type":0,"val":"admin","end":""},{"old":"/admin/payments/categories","type":0,"val":"payments","end":""},{"old":"/admin/payments/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['payments.categories.postCreate']['types'],
  },
  'payments.categories.postEdit': {
    methods: ["PATCH"],
    pattern: '/admin/payments/categories/:id',
    tokens: [{"old":"/admin/payments/categories/:id","type":0,"val":"admin","end":""},{"old":"/admin/payments/categories/:id","type":0,"val":"payments","end":""},{"old":"/admin/payments/categories/:id","type":0,"val":"categories","end":""},{"old":"/admin/payments/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['payments.categories.postEdit']['types'],
  },
  'payments.categories.delete': {
    methods: ["DELETE"],
    pattern: '/admin/payments/categories/:id',
    tokens: [{"old":"/admin/payments/categories/:id","type":0,"val":"admin","end":""},{"old":"/admin/payments/categories/:id","type":0,"val":"payments","end":""},{"old":"/admin/payments/categories/:id","type":0,"val":"categories","end":""},{"old":"/admin/payments/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['payments.categories.delete']['types'],
  },
  'payments.methods.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/payments/methods',
    tokens: [{"old":"/admin/payments/methods","type":0,"val":"admin","end":""},{"old":"/admin/payments/methods","type":0,"val":"payments","end":""},{"old":"/admin/payments/methods","type":0,"val":"methods","end":""}],
    types: placeholder as Registry['payments.methods.index']['types'],
  },
  'payments.methods.postCreate': {
    methods: ["POST"],
    pattern: '/admin/payments/methods',
    tokens: [{"old":"/admin/payments/methods","type":0,"val":"admin","end":""},{"old":"/admin/payments/methods","type":0,"val":"payments","end":""},{"old":"/admin/payments/methods","type":0,"val":"methods","end":""}],
    types: placeholder as Registry['payments.methods.postCreate']['types'],
  },
  'payments.methods.getJson': {
    methods: ["GET","HEAD"],
    pattern: '/admin/payments/methods/get-json',
    tokens: [{"old":"/admin/payments/methods/get-json","type":0,"val":"admin","end":""},{"old":"/admin/payments/methods/get-json","type":0,"val":"payments","end":""},{"old":"/admin/payments/methods/get-json","type":0,"val":"methods","end":""},{"old":"/admin/payments/methods/get-json","type":0,"val":"get-json","end":""}],
    types: placeholder as Registry['payments.methods.getJson']['types'],
  },
  'payments.methods.detailPaymentMethod': {
    methods: ["GET","HEAD"],
    pattern: '/admin/payments/methods/:id',
    tokens: [{"old":"/admin/payments/methods/:id","type":0,"val":"admin","end":""},{"old":"/admin/payments/methods/:id","type":0,"val":"payments","end":""},{"old":"/admin/payments/methods/:id","type":0,"val":"methods","end":""},{"old":"/admin/payments/methods/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['payments.methods.detailPaymentMethod']['types'],
  },
  'payments.methods.postEdit': {
    methods: ["PATCH"],
    pattern: '/admin/payments/methods/:id',
    tokens: [{"old":"/admin/payments/methods/:id","type":0,"val":"admin","end":""},{"old":"/admin/payments/methods/:id","type":0,"val":"payments","end":""},{"old":"/admin/payments/methods/:id","type":0,"val":"methods","end":""},{"old":"/admin/payments/methods/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['payments.methods.postEdit']['types'],
  },
  'payments.methods.delete': {
    methods: ["DELETE"],
    pattern: '/admin/payments/methods/:id',
    tokens: [{"old":"/admin/payments/methods/:id","type":0,"val":"admin","end":""},{"old":"/admin/payments/methods/:id","type":0,"val":"payments","end":""},{"old":"/admin/payments/methods/:id","type":0,"val":"methods","end":""},{"old":"/admin/payments/methods/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['payments.methods.delete']['types'],
  },
  'offers.indexVoucher': {
    methods: ["GET","HEAD"],
    pattern: '/admin/offers/voucher',
    tokens: [{"old":"/admin/offers/voucher","type":0,"val":"admin","end":""},{"old":"/admin/offers/voucher","type":0,"val":"offers","end":""},{"old":"/admin/offers/voucher","type":0,"val":"voucher","end":""}],
    types: placeholder as Registry['offers.indexVoucher']['types'],
  },
  'offers.createVoucher': {
    methods: ["GET","HEAD"],
    pattern: '/admin/offers/voucher/create',
    tokens: [{"old":"/admin/offers/voucher/create","type":0,"val":"admin","end":""},{"old":"/admin/offers/voucher/create","type":0,"val":"offers","end":""},{"old":"/admin/offers/voucher/create","type":0,"val":"voucher","end":""},{"old":"/admin/offers/voucher/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['offers.createVoucher']['types'],
  },
  'offers.editVoucher': {
    methods: ["GET","HEAD"],
    pattern: '/admin/offers/voucher/:id/edit',
    tokens: [{"old":"/admin/offers/voucher/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/offers/voucher/:id/edit","type":0,"val":"offers","end":""},{"old":"/admin/offers/voucher/:id/edit","type":0,"val":"voucher","end":""},{"old":"/admin/offers/voucher/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/offers/voucher/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['offers.editVoucher']['types'],
  },
  'offers.indexDiscount': {
    methods: ["GET","HEAD"],
    pattern: '/admin/offers/discount',
    tokens: [{"old":"/admin/offers/discount","type":0,"val":"admin","end":""},{"old":"/admin/offers/discount","type":0,"val":"offers","end":""},{"old":"/admin/offers/discount","type":0,"val":"discount","end":""}],
    types: placeholder as Registry['offers.indexDiscount']['types'],
  },
  'offers.createDiscount': {
    methods: ["GET","HEAD"],
    pattern: '/admin/offers/discount/create',
    tokens: [{"old":"/admin/offers/discount/create","type":0,"val":"admin","end":""},{"old":"/admin/offers/discount/create","type":0,"val":"offers","end":""},{"old":"/admin/offers/discount/create","type":0,"val":"discount","end":""},{"old":"/admin/offers/discount/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['offers.createDiscount']['types'],
  },
  'offers.editDiscount': {
    methods: ["GET","HEAD"],
    pattern: '/admin/offers/discount/:id/edit',
    tokens: [{"old":"/admin/offers/discount/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/offers/discount/:id/edit","type":0,"val":"offers","end":""},{"old":"/admin/offers/discount/:id/edit","type":0,"val":"discount","end":""},{"old":"/admin/offers/discount/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/offers/discount/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['offers.editDiscount']['types'],
  },
  'offers.indexFlashSale': {
    methods: ["GET","HEAD"],
    pattern: '/admin/offers/flash-sale',
    tokens: [{"old":"/admin/offers/flash-sale","type":0,"val":"admin","end":""},{"old":"/admin/offers/flash-sale","type":0,"val":"offers","end":""},{"old":"/admin/offers/flash-sale","type":0,"val":"flash-sale","end":""}],
    types: placeholder as Registry['offers.indexFlashSale']['types'],
  },
  'offers.createFlashSale': {
    methods: ["GET","HEAD"],
    pattern: '/admin/offers/flash-sale/create',
    tokens: [{"old":"/admin/offers/flash-sale/create","type":0,"val":"admin","end":""},{"old":"/admin/offers/flash-sale/create","type":0,"val":"offers","end":""},{"old":"/admin/offers/flash-sale/create","type":0,"val":"flash-sale","end":""},{"old":"/admin/offers/flash-sale/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['offers.createFlashSale']['types'],
  },
  'offers.editFlashSale': {
    methods: ["GET","HEAD"],
    pattern: '/admin/offers/flash-sale/:id/edit',
    tokens: [{"old":"/admin/offers/flash-sale/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/offers/flash-sale/:id/edit","type":0,"val":"offers","end":""},{"old":"/admin/offers/flash-sale/:id/edit","type":0,"val":"flash-sale","end":""},{"old":"/admin/offers/flash-sale/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/offers/flash-sale/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['offers.editFlashSale']['types'],
  },
  'offers.used': {
    methods: ["GET","HEAD"],
    pattern: '/admin/offers/history',
    tokens: [{"old":"/admin/offers/history","type":0,"val":"admin","end":""},{"old":"/admin/offers/history","type":0,"val":"offers","end":""},{"old":"/admin/offers/history","type":0,"val":"history","end":""}],
    types: placeholder as Registry['offers.used']['types'],
  },
  'offers.postCreate': {
    methods: ["POST"],
    pattern: '/admin/offers/create',
    tokens: [{"old":"/admin/offers/create","type":0,"val":"admin","end":""},{"old":"/admin/offers/create","type":0,"val":"offers","end":""},{"old":"/admin/offers/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['offers.postCreate']['types'],
  },
  'offers.postUpdate': {
    methods: ["PATCH"],
    pattern: '/admin/offers/:id/edit',
    tokens: [{"old":"/admin/offers/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/offers/:id/edit","type":0,"val":"offers","end":""},{"old":"/admin/offers/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/offers/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['offers.postUpdate']['types'],
  },
  'offers.delete': {
    methods: ["DELETE"],
    pattern: '/admin/offers/:id',
    tokens: [{"old":"/admin/offers/:id","type":0,"val":"admin","end":""},{"old":"/admin/offers/:id","type":0,"val":"offers","end":""},{"old":"/admin/offers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['offers.delete']['types'],
  },
  'offers.connectUser': {
    methods: ["POST"],
    pattern: '/admin/offers/:id/connect/user',
    tokens: [{"old":"/admin/offers/:id/connect/user","type":0,"val":"admin","end":""},{"old":"/admin/offers/:id/connect/user","type":0,"val":"offers","end":""},{"old":"/admin/offers/:id/connect/user","type":1,"val":"id","end":""},{"old":"/admin/offers/:id/connect/user","type":0,"val":"connect","end":""},{"old":"/admin/offers/:id/connect/user","type":0,"val":"user","end":""}],
    types: placeholder as Registry['offers.connectUser']['types'],
  },
  'offers.disconnectUser': {
    methods: ["POST"],
    pattern: '/admin/offers/:id/disconnect/user',
    tokens: [{"old":"/admin/offers/:id/disconnect/user","type":0,"val":"admin","end":""},{"old":"/admin/offers/:id/disconnect/user","type":0,"val":"offers","end":""},{"old":"/admin/offers/:id/disconnect/user","type":1,"val":"id","end":""},{"old":"/admin/offers/:id/disconnect/user","type":0,"val":"disconnect","end":""},{"old":"/admin/offers/:id/disconnect/user","type":0,"val":"user","end":""}],
    types: placeholder as Registry['offers.disconnectUser']['types'],
  },
  'offers.connectProduct': {
    methods: ["POST"],
    pattern: '/admin/offers/:id/connect/product',
    tokens: [{"old":"/admin/offers/:id/connect/product","type":0,"val":"admin","end":""},{"old":"/admin/offers/:id/connect/product","type":0,"val":"offers","end":""},{"old":"/admin/offers/:id/connect/product","type":1,"val":"id","end":""},{"old":"/admin/offers/:id/connect/product","type":0,"val":"connect","end":""},{"old":"/admin/offers/:id/connect/product","type":0,"val":"product","end":""}],
    types: placeholder as Registry['offers.connectProduct']['types'],
  },
  'offers.disconnectProduct': {
    methods: ["POST"],
    pattern: '/admin/offers/:id/disconnect/product',
    tokens: [{"old":"/admin/offers/:id/disconnect/product","type":0,"val":"admin","end":""},{"old":"/admin/offers/:id/disconnect/product","type":0,"val":"offers","end":""},{"old":"/admin/offers/:id/disconnect/product","type":1,"val":"id","end":""},{"old":"/admin/offers/:id/disconnect/product","type":0,"val":"disconnect","end":""},{"old":"/admin/offers/:id/disconnect/product","type":0,"val":"product","end":""}],
    types: placeholder as Registry['offers.disconnectProduct']['types'],
  },
  'offers.connectPaymentMethod': {
    methods: ["POST"],
    pattern: '/admin/offers/:id/connect/payment-method',
    tokens: [{"old":"/admin/offers/:id/connect/payment-method","type":0,"val":"admin","end":""},{"old":"/admin/offers/:id/connect/payment-method","type":0,"val":"offers","end":""},{"old":"/admin/offers/:id/connect/payment-method","type":1,"val":"id","end":""},{"old":"/admin/offers/:id/connect/payment-method","type":0,"val":"connect","end":""},{"old":"/admin/offers/:id/connect/payment-method","type":0,"val":"payment-method","end":""}],
    types: placeholder as Registry['offers.connectPaymentMethod']['types'],
  },
  'offers.disconnectPaymentMethod': {
    methods: ["POST"],
    pattern: '/admin/offers/:id/disconnect/payment-method',
    tokens: [{"old":"/admin/offers/:id/disconnect/payment-method","type":0,"val":"admin","end":""},{"old":"/admin/offers/:id/disconnect/payment-method","type":0,"val":"offers","end":""},{"old":"/admin/offers/:id/disconnect/payment-method","type":1,"val":"id","end":""},{"old":"/admin/offers/:id/disconnect/payment-method","type":0,"val":"disconnect","end":""},{"old":"/admin/offers/:id/disconnect/payment-method","type":0,"val":"payment-method","end":""}],
    types: placeholder as Registry['offers.disconnectPaymentMethod']['types'],
  },
  'offers.getOfferUsers': {
    methods: ["GET","HEAD"],
    pattern: '/admin/offers/:id/users',
    tokens: [{"old":"/admin/offers/:id/users","type":0,"val":"admin","end":""},{"old":"/admin/offers/:id/users","type":0,"val":"offers","end":""},{"old":"/admin/offers/:id/users","type":1,"val":"id","end":""},{"old":"/admin/offers/:id/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['offers.getOfferUsers']['types'],
  },
  'offers.getOfferProducts': {
    methods: ["GET","HEAD"],
    pattern: '/admin/offers/:id/products',
    tokens: [{"old":"/admin/offers/:id/products","type":0,"val":"admin","end":""},{"old":"/admin/offers/:id/products","type":0,"val":"offers","end":""},{"old":"/admin/offers/:id/products","type":1,"val":"id","end":""},{"old":"/admin/offers/:id/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['offers.getOfferProducts']['types'],
  },
  'offers.getOfferPaymentMethods': {
    methods: ["GET","HEAD"],
    pattern: '/admin/offers/:id/payment-methods',
    tokens: [{"old":"/admin/offers/:id/payment-methods","type":0,"val":"admin","end":""},{"old":"/admin/offers/:id/payment-methods","type":0,"val":"offers","end":""},{"old":"/admin/offers/:id/payment-methods","type":1,"val":"id","end":""},{"old":"/admin/offers/:id/payment-methods","type":0,"val":"payment-methods","end":""}],
    types: placeholder as Registry['offers.getOfferPaymentMethods']['types'],
  },
  'deposits.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/deposits',
    tokens: [{"old":"/admin/deposits","type":0,"val":"admin","end":""},{"old":"/admin/deposits","type":0,"val":"deposits","end":""}],
    types: placeholder as Registry['deposits.index']['types'],
  },
  'deposits.getById': {
    methods: ["GET","HEAD"],
    pattern: '/admin/deposits/:id',
    tokens: [{"old":"/admin/deposits/:id","type":0,"val":"admin","end":""},{"old":"/admin/deposits/:id","type":0,"val":"deposits","end":""},{"old":"/admin/deposits/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['deposits.getById']['types'],
  },
  'deposits.changeStatus': {
    methods: ["PATCH"],
    pattern: '/admin/deposits/:id',
    tokens: [{"old":"/admin/deposits/:id","type":0,"val":"admin","end":""},{"old":"/admin/deposits/:id","type":0,"val":"deposits","end":""},{"old":"/admin/deposits/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['deposits.changeStatus']['types'],
  },
  'order.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/orders',
    tokens: [{"old":"/admin/orders","type":0,"val":"admin","end":""},{"old":"/admin/orders","type":0,"val":"orders","end":""}],
    types: placeholder as Registry['order.index']['types'],
  },
  'order.indexPrepaid': {
    methods: ["GET","HEAD"],
    pattern: '/admin/orders/prepaid',
    tokens: [{"old":"/admin/orders/prepaid","type":0,"val":"admin","end":""},{"old":"/admin/orders/prepaid","type":0,"val":"orders","end":""},{"old":"/admin/orders/prepaid","type":0,"val":"prepaid","end":""}],
    types: placeholder as Registry['order.indexPrepaid']['types'],
  },
  'order.getById': {
    methods: ["GET","HEAD"],
    pattern: '/admin/orders/:id',
    tokens: [{"old":"/admin/orders/:id","type":0,"val":"admin","end":""},{"old":"/admin/orders/:id","type":0,"val":"orders","end":""},{"old":"/admin/orders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['order.getById']['types'],
  },
  'order.changePaymentStatus': {
    methods: ["PATCH"],
    pattern: '/admin/orders/:id/change-payment-status',
    tokens: [{"old":"/admin/orders/:id/change-payment-status","type":0,"val":"admin","end":""},{"old":"/admin/orders/:id/change-payment-status","type":0,"val":"orders","end":""},{"old":"/admin/orders/:id/change-payment-status","type":1,"val":"id","end":""},{"old":"/admin/orders/:id/change-payment-status","type":0,"val":"change-payment-status","end":""}],
    types: placeholder as Registry['order.changePaymentStatus']['types'],
  },
  'order.changeOrderStatus': {
    methods: ["PATCH"],
    pattern: '/admin/orders/:id/change-order-status',
    tokens: [{"old":"/admin/orders/:id/change-order-status","type":0,"val":"admin","end":""},{"old":"/admin/orders/:id/change-order-status","type":0,"val":"orders","end":""},{"old":"/admin/orders/:id/change-order-status","type":1,"val":"id","end":""},{"old":"/admin/orders/:id/change-order-status","type":0,"val":"change-order-status","end":""}],
    types: placeholder as Registry['order.changeOrderStatus']['types'],
  },
  'order.changeRefundStatus': {
    methods: ["PATCH"],
    pattern: '/admin/orders/:id/change-refund-status',
    tokens: [{"old":"/admin/orders/:id/change-refund-status","type":0,"val":"admin","end":""},{"old":"/admin/orders/:id/change-refund-status","type":0,"val":"orders","end":""},{"old":"/admin/orders/:id/change-refund-status","type":1,"val":"id","end":""},{"old":"/admin/orders/:id/change-refund-status","type":0,"val":"change-refund-status","end":""}],
    types: placeholder as Registry['order.changeRefundStatus']['types'],
  },
  'order.refundOrder': {
    methods: ["POST"],
    pattern: '/admin/orders/:id/refund',
    tokens: [{"old":"/admin/orders/:id/refund","type":0,"val":"admin","end":""},{"old":"/admin/orders/:id/refund","type":0,"val":"orders","end":""},{"old":"/admin/orders/:id/refund","type":1,"val":"id","end":""},{"old":"/admin/orders/:id/refund","type":0,"val":"refund","end":""}],
    types: placeholder as Registry['order.refundOrder']['types'],
  },
  'balanceMutations.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/balance-mutations',
    tokens: [{"old":"/admin/balance-mutations","type":0,"val":"admin","end":""},{"old":"/admin/balance-mutations","type":0,"val":"balance-mutations","end":""}],
    types: placeholder as Registry['balanceMutations.index']['types'],
  },
  'configFastMenu.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/config/home/fast-menu',
    tokens: [{"old":"/admin/config/home/fast-menu","type":0,"val":"admin","end":""},{"old":"/admin/config/home/fast-menu","type":0,"val":"config","end":""},{"old":"/admin/config/home/fast-menu","type":0,"val":"home","end":""},{"old":"/admin/config/home/fast-menu","type":0,"val":"fast-menu","end":""}],
    types: placeholder as Registry['configFastMenu.index']['types'],
  },
  'configFastMenu.postCreate': {
    methods: ["POST"],
    pattern: '/admin/config/home/fast-menu',
    tokens: [{"old":"/admin/config/home/fast-menu","type":0,"val":"admin","end":""},{"old":"/admin/config/home/fast-menu","type":0,"val":"config","end":""},{"old":"/admin/config/home/fast-menu","type":0,"val":"home","end":""},{"old":"/admin/config/home/fast-menu","type":0,"val":"fast-menu","end":""}],
    types: placeholder as Registry['configFastMenu.postCreate']['types'],
  },
  'configFastMenu.connectProductToSection': {
    methods: ["POST"],
    pattern: '/admin/config/home/fast-menu/:id/connect-product',
    tokens: [{"old":"/admin/config/home/fast-menu/:id/connect-product","type":0,"val":"admin","end":""},{"old":"/admin/config/home/fast-menu/:id/connect-product","type":0,"val":"config","end":""},{"old":"/admin/config/home/fast-menu/:id/connect-product","type":0,"val":"home","end":""},{"old":"/admin/config/home/fast-menu/:id/connect-product","type":0,"val":"fast-menu","end":""},{"old":"/admin/config/home/fast-menu/:id/connect-product","type":1,"val":"id","end":""},{"old":"/admin/config/home/fast-menu/:id/connect-product","type":0,"val":"connect-product","end":""}],
    types: placeholder as Registry['configFastMenu.connectProductToSection']['types'],
  },
  'configFastMenu.bulkConnectProductToSection': {
    methods: ["POST"],
    pattern: '/admin/config/home/fast-menu/:id/bulk-connect-product',
    tokens: [{"old":"/admin/config/home/fast-menu/:id/bulk-connect-product","type":0,"val":"admin","end":""},{"old":"/admin/config/home/fast-menu/:id/bulk-connect-product","type":0,"val":"config","end":""},{"old":"/admin/config/home/fast-menu/:id/bulk-connect-product","type":0,"val":"home","end":""},{"old":"/admin/config/home/fast-menu/:id/bulk-connect-product","type":0,"val":"fast-menu","end":""},{"old":"/admin/config/home/fast-menu/:id/bulk-connect-product","type":1,"val":"id","end":""},{"old":"/admin/config/home/fast-menu/:id/bulk-connect-product","type":0,"val":"bulk-connect-product","end":""}],
    types: placeholder as Registry['configFastMenu.bulkConnectProductToSection']['types'],
  },
  'config_fast_menu.disconnect_product_from_section': {
    methods: ["POST"],
    pattern: '/admin/config/home/fast-menu/:id/disconnect-product',
    tokens: [{"old":"/admin/config/home/fast-menu/:id/disconnect-product","type":0,"val":"admin","end":""},{"old":"/admin/config/home/fast-menu/:id/disconnect-product","type":0,"val":"config","end":""},{"old":"/admin/config/home/fast-menu/:id/disconnect-product","type":0,"val":"home","end":""},{"old":"/admin/config/home/fast-menu/:id/disconnect-product","type":0,"val":"fast-menu","end":""},{"old":"/admin/config/home/fast-menu/:id/disconnect-product","type":1,"val":"id","end":""},{"old":"/admin/config/home/fast-menu/:id/disconnect-product","type":0,"val":"disconnect-product","end":""}],
    types: placeholder as Registry['config_fast_menu.disconnect_product_from_section']['types'],
  },
  'configFastMenu.detail': {
    methods: ["GET","HEAD"],
    pattern: '/admin/config/home/fast-menu/:id',
    tokens: [{"old":"/admin/config/home/fast-menu/:id","type":0,"val":"admin","end":""},{"old":"/admin/config/home/fast-menu/:id","type":0,"val":"config","end":""},{"old":"/admin/config/home/fast-menu/:id","type":0,"val":"home","end":""},{"old":"/admin/config/home/fast-menu/:id","type":0,"val":"fast-menu","end":""},{"old":"/admin/config/home/fast-menu/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['configFastMenu.detail']['types'],
  },
  'configFastMenu.postEdit': {
    methods: ["PATCH"],
    pattern: '/admin/config/home/fast-menu/:id',
    tokens: [{"old":"/admin/config/home/fast-menu/:id","type":0,"val":"admin","end":""},{"old":"/admin/config/home/fast-menu/:id","type":0,"val":"config","end":""},{"old":"/admin/config/home/fast-menu/:id","type":0,"val":"home","end":""},{"old":"/admin/config/home/fast-menu/:id","type":0,"val":"fast-menu","end":""},{"old":"/admin/config/home/fast-menu/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['configFastMenu.postEdit']['types'],
  },
  'configFastMenu.postDelete': {
    methods: ["DELETE"],
    pattern: '/admin/config/home/fast-menu/:id',
    tokens: [{"old":"/admin/config/home/fast-menu/:id","type":0,"val":"admin","end":""},{"old":"/admin/config/home/fast-menu/:id","type":0,"val":"config","end":""},{"old":"/admin/config/home/fast-menu/:id","type":0,"val":"home","end":""},{"old":"/admin/config/home/fast-menu/:id","type":0,"val":"fast-menu","end":""},{"old":"/admin/config/home/fast-menu/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['configFastMenu.postDelete']['types'],
  },
  'configHomes.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/config/home/product-sections',
    tokens: [{"old":"/admin/config/home/product-sections","type":0,"val":"admin","end":""},{"old":"/admin/config/home/product-sections","type":0,"val":"config","end":""},{"old":"/admin/config/home/product-sections","type":0,"val":"home","end":""},{"old":"/admin/config/home/product-sections","type":0,"val":"product-sections","end":""}],
    types: placeholder as Registry['configHomes.index']['types'],
  },
  'configHomes.postCreate': {
    methods: ["POST"],
    pattern: '/admin/config/home/product-sections',
    tokens: [{"old":"/admin/config/home/product-sections","type":0,"val":"admin","end":""},{"old":"/admin/config/home/product-sections","type":0,"val":"config","end":""},{"old":"/admin/config/home/product-sections","type":0,"val":"home","end":""},{"old":"/admin/config/home/product-sections","type":0,"val":"product-sections","end":""}],
    types: placeholder as Registry['configHomes.postCreate']['types'],
  },
  'configHomes.connectProductToSection': {
    methods: ["POST"],
    pattern: '/admin/config/home/product-sections/:id/connect-product',
    tokens: [{"old":"/admin/config/home/product-sections/:id/connect-product","type":0,"val":"admin","end":""},{"old":"/admin/config/home/product-sections/:id/connect-product","type":0,"val":"config","end":""},{"old":"/admin/config/home/product-sections/:id/connect-product","type":0,"val":"home","end":""},{"old":"/admin/config/home/product-sections/:id/connect-product","type":0,"val":"product-sections","end":""},{"old":"/admin/config/home/product-sections/:id/connect-product","type":1,"val":"id","end":""},{"old":"/admin/config/home/product-sections/:id/connect-product","type":0,"val":"connect-product","end":""}],
    types: placeholder as Registry['configHomes.connectProductToSection']['types'],
  },
  'configHomes.bulkConnectProductToSection': {
    methods: ["POST"],
    pattern: '/admin/config/home/product-sections/:id/bulk-connect-product',
    tokens: [{"old":"/admin/config/home/product-sections/:id/bulk-connect-product","type":0,"val":"admin","end":""},{"old":"/admin/config/home/product-sections/:id/bulk-connect-product","type":0,"val":"config","end":""},{"old":"/admin/config/home/product-sections/:id/bulk-connect-product","type":0,"val":"home","end":""},{"old":"/admin/config/home/product-sections/:id/bulk-connect-product","type":0,"val":"product-sections","end":""},{"old":"/admin/config/home/product-sections/:id/bulk-connect-product","type":1,"val":"id","end":""},{"old":"/admin/config/home/product-sections/:id/bulk-connect-product","type":0,"val":"bulk-connect-product","end":""}],
    types: placeholder as Registry['configHomes.bulkConnectProductToSection']['types'],
  },
  'config_homes.disconnect_product_from_section': {
    methods: ["POST"],
    pattern: '/admin/config/home/product-sections/:id/disconnect-product',
    tokens: [{"old":"/admin/config/home/product-sections/:id/disconnect-product","type":0,"val":"admin","end":""},{"old":"/admin/config/home/product-sections/:id/disconnect-product","type":0,"val":"config","end":""},{"old":"/admin/config/home/product-sections/:id/disconnect-product","type":0,"val":"home","end":""},{"old":"/admin/config/home/product-sections/:id/disconnect-product","type":0,"val":"product-sections","end":""},{"old":"/admin/config/home/product-sections/:id/disconnect-product","type":1,"val":"id","end":""},{"old":"/admin/config/home/product-sections/:id/disconnect-product","type":0,"val":"disconnect-product","end":""}],
    types: placeholder as Registry['config_homes.disconnect_product_from_section']['types'],
  },
  'configHomes.detail': {
    methods: ["GET","HEAD"],
    pattern: '/admin/config/home/product-sections/:id',
    tokens: [{"old":"/admin/config/home/product-sections/:id","type":0,"val":"admin","end":""},{"old":"/admin/config/home/product-sections/:id","type":0,"val":"config","end":""},{"old":"/admin/config/home/product-sections/:id","type":0,"val":"home","end":""},{"old":"/admin/config/home/product-sections/:id","type":0,"val":"product-sections","end":""},{"old":"/admin/config/home/product-sections/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['configHomes.detail']['types'],
  },
  'configHomes.postEdit': {
    methods: ["PATCH"],
    pattern: '/admin/config/home/product-sections/:id',
    tokens: [{"old":"/admin/config/home/product-sections/:id","type":0,"val":"admin","end":""},{"old":"/admin/config/home/product-sections/:id","type":0,"val":"config","end":""},{"old":"/admin/config/home/product-sections/:id","type":0,"val":"home","end":""},{"old":"/admin/config/home/product-sections/:id","type":0,"val":"product-sections","end":""},{"old":"/admin/config/home/product-sections/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['configHomes.postEdit']['types'],
  },
  'configHomes.postDelete': {
    methods: ["DELETE"],
    pattern: '/admin/config/home/product-sections/:id',
    tokens: [{"old":"/admin/config/home/product-sections/:id","type":0,"val":"admin","end":""},{"old":"/admin/config/home/product-sections/:id","type":0,"val":"config","end":""},{"old":"/admin/config/home/product-sections/:id","type":0,"val":"home","end":""},{"old":"/admin/config/home/product-sections/:id","type":0,"val":"product-sections","end":""},{"old":"/admin/config/home/product-sections/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['configHomes.postDelete']['types'],
  },
  'banners.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/config/home/banner',
    tokens: [{"old":"/admin/config/home/banner","type":0,"val":"admin","end":""},{"old":"/admin/config/home/banner","type":0,"val":"config","end":""},{"old":"/admin/config/home/banner","type":0,"val":"home","end":""},{"old":"/admin/config/home/banner","type":0,"val":"banner","end":""}],
    types: placeholder as Registry['banners.index']['types'],
  },
  'banners.postCreate': {
    methods: ["POST"],
    pattern: '/admin/config/home/banner',
    tokens: [{"old":"/admin/config/home/banner","type":0,"val":"admin","end":""},{"old":"/admin/config/home/banner","type":0,"val":"config","end":""},{"old":"/admin/config/home/banner","type":0,"val":"home","end":""},{"old":"/admin/config/home/banner","type":0,"val":"banner","end":""}],
    types: placeholder as Registry['banners.postCreate']['types'],
  },
  'banners.delete': {
    methods: ["DELETE"],
    pattern: '/admin/config/home/banner/:id',
    tokens: [{"old":"/admin/config/home/banner/:id","type":0,"val":"admin","end":""},{"old":"/admin/config/home/banner/:id","type":0,"val":"config","end":""},{"old":"/admin/config/home/banner/:id","type":0,"val":"home","end":""},{"old":"/admin/config/home/banner/:id","type":0,"val":"banner","end":""},{"old":"/admin/config/home/banner/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['banners.delete']['types'],
  },
  'config_settings.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/config/settings/general',
    tokens: [{"old":"/admin/config/settings/general","type":0,"val":"admin","end":""},{"old":"/admin/config/settings/general","type":0,"val":"config","end":""},{"old":"/admin/config/settings/general","type":0,"val":"settings","end":""},{"old":"/admin/config/settings/general","type":0,"val":"general","end":""}],
    types: placeholder as Registry['config_settings.index']['types'],
  },
  'config_settings.update': {
    methods: ["PATCH"],
    pattern: '/admin/config/settings/general',
    tokens: [{"old":"/admin/config/settings/general","type":0,"val":"admin","end":""},{"old":"/admin/config/settings/general","type":0,"val":"config","end":""},{"old":"/admin/config/settings/general","type":0,"val":"settings","end":""},{"old":"/admin/config/settings/general","type":0,"val":"general","end":""}],
    types: placeholder as Registry['config_settings.update']['types'],
  },
  'pages.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/config/pages',
    tokens: [{"old":"/admin/config/pages","type":0,"val":"admin","end":""},{"old":"/admin/config/pages","type":0,"val":"config","end":""},{"old":"/admin/config/pages","type":0,"val":"pages","end":""}],
    types: placeholder as Registry['pages.index']['types'],
  },
  'pages.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/config/pages/create',
    tokens: [{"old":"/admin/config/pages/create","type":0,"val":"admin","end":""},{"old":"/admin/config/pages/create","type":0,"val":"config","end":""},{"old":"/admin/config/pages/create","type":0,"val":"pages","end":""},{"old":"/admin/config/pages/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['pages.create']['types'],
  },
  'pages.store': {
    methods: ["POST"],
    pattern: '/admin/config/pages',
    tokens: [{"old":"/admin/config/pages","type":0,"val":"admin","end":""},{"old":"/admin/config/pages","type":0,"val":"config","end":""},{"old":"/admin/config/pages","type":0,"val":"pages","end":""}],
    types: placeholder as Registry['pages.store']['types'],
  },
  'pages.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/config/pages/:id/edit',
    tokens: [{"old":"/admin/config/pages/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/config/pages/:id/edit","type":0,"val":"config","end":""},{"old":"/admin/config/pages/:id/edit","type":0,"val":"pages","end":""},{"old":"/admin/config/pages/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/config/pages/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['pages.edit']['types'],
  },
  'pages.update': {
    methods: ["PATCH"],
    pattern: '/admin/config/pages/:id',
    tokens: [{"old":"/admin/config/pages/:id","type":0,"val":"admin","end":""},{"old":"/admin/config/pages/:id","type":0,"val":"config","end":""},{"old":"/admin/config/pages/:id","type":0,"val":"pages","end":""},{"old":"/admin/config/pages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['pages.update']['types'],
  },
  'pages.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/config/pages/:id',
    tokens: [{"old":"/admin/config/pages/:id","type":0,"val":"admin","end":""},{"old":"/admin/config/pages/:id","type":0,"val":"config","end":""},{"old":"/admin/config/pages/:id","type":0,"val":"pages","end":""},{"old":"/admin/config/pages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['pages.destroy']['types'],
  },
  'articleCategories.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/blog/categories',
    tokens: [{"old":"/admin/blog/categories","type":0,"val":"admin","end":""},{"old":"/admin/blog/categories","type":0,"val":"blog","end":""},{"old":"/admin/blog/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['articleCategories.index']['types'],
  },
  'articleCategories.store': {
    methods: ["POST"],
    pattern: '/admin/blog/categories',
    tokens: [{"old":"/admin/blog/categories","type":0,"val":"admin","end":""},{"old":"/admin/blog/categories","type":0,"val":"blog","end":""},{"old":"/admin/blog/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['articleCategories.store']['types'],
  },
  'articleCategories.getJson': {
    methods: ["GET","HEAD"],
    pattern: '/admin/blog/categories/get-json',
    tokens: [{"old":"/admin/blog/categories/get-json","type":0,"val":"admin","end":""},{"old":"/admin/blog/categories/get-json","type":0,"val":"blog","end":""},{"old":"/admin/blog/categories/get-json","type":0,"val":"categories","end":""},{"old":"/admin/blog/categories/get-json","type":0,"val":"get-json","end":""}],
    types: placeholder as Registry['articleCategories.getJson']['types'],
  },
  'articleCategories.update': {
    methods: ["PATCH"],
    pattern: '/admin/blog/categories/:id',
    tokens: [{"old":"/admin/blog/categories/:id","type":0,"val":"admin","end":""},{"old":"/admin/blog/categories/:id","type":0,"val":"blog","end":""},{"old":"/admin/blog/categories/:id","type":0,"val":"categories","end":""},{"old":"/admin/blog/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['articleCategories.update']['types'],
  },
  'articleCategories.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/blog/categories/:id',
    tokens: [{"old":"/admin/blog/categories/:id","type":0,"val":"admin","end":""},{"old":"/admin/blog/categories/:id","type":0,"val":"blog","end":""},{"old":"/admin/blog/categories/:id","type":0,"val":"categories","end":""},{"old":"/admin/blog/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['articleCategories.destroy']['types'],
  },
  'articles.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/blog/articles',
    tokens: [{"old":"/admin/blog/articles","type":0,"val":"admin","end":""},{"old":"/admin/blog/articles","type":0,"val":"blog","end":""},{"old":"/admin/blog/articles","type":0,"val":"articles","end":""}],
    types: placeholder as Registry['articles.index']['types'],
  },
  'articles.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/blog/articles/create',
    tokens: [{"old":"/admin/blog/articles/create","type":0,"val":"admin","end":""},{"old":"/admin/blog/articles/create","type":0,"val":"blog","end":""},{"old":"/admin/blog/articles/create","type":0,"val":"articles","end":""},{"old":"/admin/blog/articles/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['articles.create']['types'],
  },
  'articles.store': {
    methods: ["POST"],
    pattern: '/admin/blog/articles',
    tokens: [{"old":"/admin/blog/articles","type":0,"val":"admin","end":""},{"old":"/admin/blog/articles","type":0,"val":"blog","end":""},{"old":"/admin/blog/articles","type":0,"val":"articles","end":""}],
    types: placeholder as Registry['articles.store']['types'],
  },
  'articles.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/blog/articles/:id/edit',
    tokens: [{"old":"/admin/blog/articles/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/blog/articles/:id/edit","type":0,"val":"blog","end":""},{"old":"/admin/blog/articles/:id/edit","type":0,"val":"articles","end":""},{"old":"/admin/blog/articles/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/blog/articles/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['articles.edit']['types'],
  },
  'articles.update': {
    methods: ["PATCH"],
    pattern: '/admin/blog/articles/:id',
    tokens: [{"old":"/admin/blog/articles/:id","type":0,"val":"admin","end":""},{"old":"/admin/blog/articles/:id","type":0,"val":"blog","end":""},{"old":"/admin/blog/articles/:id","type":0,"val":"articles","end":""},{"old":"/admin/blog/articles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['articles.update']['types'],
  },
  'articles.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/blog/articles/:id',
    tokens: [{"old":"/admin/blog/articles/:id","type":0,"val":"admin","end":""},{"old":"/admin/blog/articles/:id","type":0,"val":"blog","end":""},{"old":"/admin/blog/articles/:id","type":0,"val":"articles","end":""},{"old":"/admin/blog/articles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['articles.destroy']['types'],
  },
  'articles.togglePublish': {
    methods: ["POST"],
    pattern: '/admin/blog/articles/:id/toggle-publish',
    tokens: [{"old":"/admin/blog/articles/:id/toggle-publish","type":0,"val":"admin","end":""},{"old":"/admin/blog/articles/:id/toggle-publish","type":0,"val":"blog","end":""},{"old":"/admin/blog/articles/:id/toggle-publish","type":0,"val":"articles","end":""},{"old":"/admin/blog/articles/:id/toggle-publish","type":1,"val":"id","end":""},{"old":"/admin/blog/articles/:id/toggle-publish","type":0,"val":"toggle-publish","end":""}],
    types: placeholder as Registry['articles.togglePublish']['types'],
  },
  'articles.toggleFeatured': {
    methods: ["POST"],
    pattern: '/admin/blog/articles/:id/toggle-featured',
    tokens: [{"old":"/admin/blog/articles/:id/toggle-featured","type":0,"val":"admin","end":""},{"old":"/admin/blog/articles/:id/toggle-featured","type":0,"val":"blog","end":""},{"old":"/admin/blog/articles/:id/toggle-featured","type":0,"val":"articles","end":""},{"old":"/admin/blog/articles/:id/toggle-featured","type":1,"val":"id","end":""},{"old":"/admin/blog/articles/:id/toggle-featured","type":0,"val":"toggle-featured","end":""}],
    types: placeholder as Registry['articles.toggleFeatured']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
