import vine from '@vinejs/vine'

export const updateSettingsValidator = vine.object({
  maintenance_enabled: vine.boolean().optional(),
  app_name: vine.string().trim().optional().nullable(),
  app_description: vine.string().trim().optional().nullable(),
  app_icon_url: vine.string().trim().optional().nullable(),
  maintenance_banner_image_url: vine.string().trim().optional().nullable(),
  app_version: vine.string().trim().optional().nullable(),
  api_version: vine.string().trim().optional().nullable(),
  contact_email: vine.string().trim().optional().nullable(),
  contact_whatsapp: vine.string().trim().optional().nullable(),
  contact_telegram: vine.string().trim().optional().nullable(),
  contact_instagram: vine.string().trim().optional().nullable(),
  contact_facebook: vine.string().trim().optional().nullable(),
  contact_tiktok: vine.string().trim().optional().nullable(),
  contact_support_phone: vine.string().trim().optional().nullable(),
  contact_support_name: vine.string().trim().optional().nullable(),
  contact_website: vine.string().trim().optional().nullable(),
  app_ig_name: vine.string().trim().optional().nullable(),
  app_ig_url: vine.string().trim().optional().nullable(),
  app_fb_name: vine.string().trim().optional().nullable(),
  app_fb_url: vine.string().trim().optional().nullable(),
  app_tt_name: vine.string().trim().optional().nullable(),
  app_tt_url: vine.string().trim().optional().nullable(),
  app_tg_name: vine.string().trim().optional().nullable(),
  app_tg_url: vine.string().trim().optional().nullable(),
  app_tw_name: vine.string().trim().optional().nullable(),
  app_tw_url: vine.string().trim().optional().nullable(),
  app_yt_name: vine.string().trim().optional().nullable(),
  app_yt_url: vine.string().trim().optional().nullable(),
  feature_topup: vine.boolean().optional(),
  feature_ppob: vine.boolean().optional(),
  feature_voucher: vine.boolean().optional(),
  feature_deposit: vine.boolean().optional(),
  feature_maintenance_banner: vine.boolean().optional(),
})
