/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  BalanceMutations: () => import('#controllers/balance_mutations_controller'),
  blog: {
    ArticleCategories: () => import('#controllers/blog/article_categories_controller'),
    Articles: () => import('#controllers/blog/articles_controller'),
  },
  configs: {
    Banners: () => import('#controllers/configs/banners_controller'),
    ConfigHomeFastMenu: () => import('#controllers/configs/config_home_fast_menu'),
    ConfigHomes: () => import('#controllers/configs/config_homes_controller'),
    Pages: () => import('#controllers/configs/pages_controller'),
    Settings: () => import('#controllers/configs/settings_controller'),
  },
  Deposits: () => import('#controllers/deposits_controller'),
  FileManagers: () => import('#controllers/file_managers_controller'),
  Home: () => import('#controllers/home_controller'),
  InputFields: () => import('#controllers/input_fields_controller'),
  Offer: () => import('#controllers/offer_controller'),
  Orders: () => import('#controllers/orders_controller'),
  Payments: () => import('#controllers/payments_controller'),
  ProductCategories: () => import('#controllers/product_categories_controller'),
  ProductCategoriesPostpaid: () => import('#controllers/product_categories_postpaid_controller'),
  ProductSubCategories: () => import('#controllers/product_sub_categories_controller'),
  Products: () => import('#controllers/products_controller'),
  Providers: () => import('#controllers/providers_controller'),
  Users: () => import('#controllers/users_controller'),
}
